### ISSUE TITLE
NO REQUIRMENT.TXT

### ISSUE THREAD

**Issue by aikuniverse** [NEUdeep/MOC-Detector-Pytorch1.4#2]
I found no requirment.txt to install the requirments.

**Comment by Haidong-Kang** [comment]
> I found no requirment.txt to install the requirments.

You are right, there is indeed no requirement.txt, I will improve the code soon, thank you

**Comment by Haidong-Kang** [comment]
Now requirement.txt is been added, you can try again.

**Comment by aikuniverse** [comment]
Thanks a lot.
